package com.example.thy.enums;

public enum ErrorCodeEnum {
    LOCATION_ALREADY_EXIST, LOCATION_NOT_FOUND, TRANSPORTATION_ALREADY_EXIST, TRANSPORTATION_NOT_FOUND, GENERAL_ERROR, TRANSPORTATION_OPERATION_DAYS_NOT_VALID, VIOLATION_ERROR, UNEXPECTED_ERROR
}
